# Trabalho 1 de Grafos: Snakes and Ladders

## Autores: 
    Nome:                       RA:
    Joao Augusto Leite          743551
    Caio Ueno                   743516
    Daniel Moura                743525

In [1]:
import networkx as nx
import numpy as np

## Funções

In [2]:
def gen_edges():
    """Gera a lista de arestas para o digrafo"""
    edges = []
    for i in range(1,36):
        edges.append((i,i+1))
        if (i+2 <= 36):
            edges.append((i, i+2))
    return edges

def gen_inversedegree(G):
    """Gera uma lista com o inverso dos graus de um grafo"""
    degrees_G = []
    for d in dict(G.out_degree()).values():
        degrees_G.append(1/d)

    return degrees_G

def power_method(P,w,it):
    """Calcula a distribuicao estacionaria usando o power method"""
    return (w @ np.linalg.matrix_power(P,it))

def Google_matrix(P,alfa):
    """Gera a matriz P barra (google matrix)"""
    P_Barra = (1-alfa)*P + (alfa/P.shape[0])*np.ones((36,36))
    return P_Barra

## Criando o grafo e gerando as arestas

In [3]:
G = nx.DiGraph()
G.add_nodes_from(range(1,37))  # Adiciona 36 vertices no grafo G
G.add_edges_from(gen_edges())  # Adiciona as arestas entre os vertices
G.add_edges_from([(2,15), (5,7), (9,27), (18,29), (25,35)]) # Adiciona as arestas 'Ladders'
G.add_edges_from([(17,4), (20,6), (32,30), (34,12), (24,16)]) # Adiciona as arestas 'Snakes'
G.add_edge(36,36)
G.remove_edges_from([(2,3),(2,4),(5,6),(9,10),(9,11),
                     (17,18),(17,19),(18,19),(18,20),
                     (20,21),(20,22),(24,25),(24,26),
                     (25,26),(25,27),(32,33),(32,34),
                     (34,35),(34,36)])
G.out_degree()

OutDegreeView({1: 2, 2: 1, 3: 2, 4: 2, 5: 1, 6: 2, 7: 2, 8: 2, 9: 1, 10: 2, 11: 2, 12: 2, 13: 2, 14: 2, 15: 2, 16: 2, 17: 1, 18: 1, 19: 2, 20: 1, 21: 2, 22: 2, 23: 2, 24: 1, 25: 1, 26: 2, 27: 2, 28: 2, 29: 2, 30: 2, 31: 2, 32: 1, 33: 2, 34: 1, 35: 1, 36: 1})

In [4]:
adj_matrix = nx.adjacency_matrix(G).toarray() # Gera a matriz de adjacencias de G
adj_matrix

array([[0, 1, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1]], dtype=int64)

In [5]:
delta = np.zeros((36,36))               
np.fill_diagonal(delta,gen_inversedegree(G)) #Gera a matriz delta
delta.diagonal() #Diagonal de Delta

array([0.5, 1. , 0.5, 0.5, 1. , 0.5, 0.5, 0.5, 1. , 0.5, 0.5, 0.5, 0.5,
       0.5, 0.5, 0.5, 1. , 1. , 0.5, 1. , 0.5, 0.5, 0.5, 1. , 1. , 0.5,
       0.5, 0.5, 0.5, 0.5, 0.5, 1. , 0.5, 1. , 1. , 1. ])

## Gerando a Matriz P

In [6]:
P = delta @ adj_matrix                     #Gera a matriz P
P

array([[0. , 0.5, 0.5, ..., 0. , 0. , 0. ],
       [0. , 0. , 0. , ..., 0. , 0. , 0. ],
       [0. , 0. , 0. , ..., 0. , 0. , 0. ],
       ...,
       [0. , 0. , 0. , ..., 0. , 0. , 0. ],
       [0. , 0. , 0. , ..., 0. , 0. , 1. ],
       [0. , 0. , 0. , ..., 0. , 0. , 1. ]])

In [7]:
w = np.zeros(36)
w[0] = 1
w # Estado inicial

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0.])

In [8]:
# Distribuicao Estacionaria de P
distr_estac_P = power_method(P,w,100)
distr_estac_P

array([0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.98761390e-03,
       1.02459294e-03, 1.02459294e-03, 1.58449826e-03, 1.34495718e-03,
       1.51010175e-03, 6.93310659e-04, 3.57394211e-04, 2.45306526e-03,
       1.44876097e-03, 2.01134833e-03, 1.78364802e-03, 1.95627878e-03,
       1.92789133e-03, 1.00844036e-03, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 1.55688234e-03, 8.02556150e-04,
       2.25594496e-03, 1.12788829e-02, 6.97705430e-03, 9.41073412e-03,
       3.59659439e-03, 1.85400481e-03, 1.85400481e-03, 9.38296846e-01])

In [22]:
print("Vertice com a maior probabilidade de ser atingido:", distr_estac_P.argmax())
print("Probabilidade de vencer o jogo:", distr_estac_P.max())
print("Soma de todas as probabilidades:", distr_estac_P.sum())

Vertice com a maior probabilidade de ser atingido: 35
Probabilidade de vencer o jogo: 0.9382968462656478
Soma de todas as probabilidades: 1.0


## Gerando a matriz P_

In [10]:
# Matriz P barra
P_ = Google_matrix(P,0.1)
P_

array([[0.00277778, 0.45277778, 0.45277778, ..., 0.00277778, 0.00277778,
        0.00277778],
       [0.00277778, 0.00277778, 0.00277778, ..., 0.00277778, 0.00277778,
        0.00277778],
       [0.00277778, 0.00277778, 0.00277778, ..., 0.00277778, 0.00277778,
        0.00277778],
       ...,
       [0.00277778, 0.00277778, 0.00277778, ..., 0.00277778, 0.00277778,
        0.00277778],
       [0.00277778, 0.00277778, 0.00277778, ..., 0.00277778, 0.00277778,
        0.90277778],
       [0.00277778, 0.00277778, 0.00277778, ..., 0.00277778, 0.00277778,
        0.90277778]])

In [11]:
# Distribuicao Estacionaria de P_
distr_estac_P_ = power_method(P_,w,100)
distr_estac_P_

array([0.00277778, 0.00402778, 0.00402778, 0.03073341, 0.01842031,
       0.02023281, 0.02846083, 0.02468992, 0.02669562, 0.01388824,
       0.00902749, 0.02797841, 0.01943043, 0.02411176, 0.02599677,
       0.03238132, 0.02904792, 0.01734937, 0.00277778, 0.00402778,
       0.00402778, 0.00459028, 0.0066559 , 0.00783856, 0.00577293,
       0.00277778, 0.02805383, 0.016652  , 0.03850984, 0.09265671,
       0.06180274, 0.07228454, 0.03058901, 0.01654284, 0.02173848,
       0.22342326])

In [23]:
distr_estac_P_.sum() 

0.9999999999999974

## Comparando as distribuições estacionárias de P e P_

In [13]:
distr_estac_P == distr_estac_P_

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [14]:
distr_estac_P_ > distr_estac_P

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False])

In [32]:
print("Vertice com a maior probabilidade de ser atingido:", distr_estac_P_.argmax())
print("Probabilidade de vencer o jogo:", distr_estac_P_.max())
print("Soma de todas as probabilidades:", distr_estac_P_.sum())

Vertice com a maior probabilidade de ser atingido: 35
Probabilidade de vencer o jogo: 0.22342326218710654
Soma de todas as probabilidades: 0.9999999999999974
